sudo: false
dist: trusty
language: cpp

git:
  submodules: true

cache:
  apt: true
  ccache: true

linux-gcc-7: &linux-gcc-7
  os: linux
  compiler: 'g++-7'
  addons:
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['g++-7', 'valgrind']
  before_install:
    - export CC="gcc-7" CXX="g++-7"

# https://docs.travis-ci.com/user/languages/c/#gcc-on-linux
matrix:
  include:
  - << : *linux-gcc-7
    env:
      - BUILD=unit
      - BUILD_TYPE=Release
  - << : *linux-gcc-7
    env:
      - BUILD=unit
      - BUILD_TYPE=Debug
  - << : *linux-gcc-7
    env:
      - BUILD=performance
      - BUILD_TYPE=Release
  - << : *linux-gcc-7
    env:
      - BUILD=performance
      - BUILD_TYPE=Debug
  - << : *linux-gcc-7
    env:
      - BUILD=header
      - BUILD_TYPE=Release
  - << : *linux-gcc-7
    env:
      - BUILD=memory
      - BUILD_TYPE=Debug

install:
  - ccache --version
  - $CXX -v
  - cmake --version

before_script:
  - mkdir ../seqan3-build
  - cd ../seqan3-build
  - cmake ../seqan3/test/${BUILD} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - |
    if test unit = "${BUILD}" || test header = "${BUILD}" || test memory = "${BUILD}"; then
      make gtest_project
    fi
  - |
    if test performance = "${BUILD}"; then
      make gbenchmark_project
    fi

script:
  - make -k
  - |
    if test memory == "${BUILD}"; then
      ctest . --test-action memcheck --output-on-failure
    else
      ctest . --output-on-failure
    fi

after_script:
  - ccache -s
