version: ~> 1.0
os: linux
dist: focal
language: cpp

branches:
  only:
  - master

# Notify us on gitter.im
notifications:
  webhooks:
    urls:
      - secure: >-
          Y5GdqwrqV3NEDv4sB76MaGl4ZzT3fXAFV6MeC7AeqaIl8eU3e96FxrFdUBGe/elN/6Ghjr4NrHp8GXSQ59owhxsduWebeiI0pyCJCF69x+QGwC
          QjJSGHchIdn+zKwkFmHfWvPMqBE+9M1qpM6c+fSA0zPcVWo3uSdCGlLf/xC+RfEnVBLnIlAs9KWmCJoBSiSIxH/htnQDUXc6D3xA6IEQy+57/K
          Bz+gzUo9FUNNx+2bRUKZHjqIIRtgOlwps2IPZeIZliRzcwlX4HklXKiygPkc7FGGu5AV26OcGnccc6ShJrXchStkJORf20jhzDtgCsAFaqWQMd
          MQoiM9QoHayZpJIbBmzzylZB1X1ID/mFpdm6ejnqWISxFpRrIUOfq6Qnap1GKJq2kpKH85sK0QJT9xAx5pbXS98LD8QymelW/J/UocFp6lm6q7
          7YnteEjWhbOFrxQvZzbS61hOa4vx68DF8/8c78mfvOiSKLraVCgihwexOdw4V1/sPW/oBPvUF+qkANDTbvBJZXZSLOe69oKxBWzBEQeStHulKk
          Z5/P90Ehnzx6BiVk4FmMQ8UVCO2xAorh5bBFnK/kkhf8R1NALXK7ihWJyI0UJb8ZT4IB3JVLKWmodVC7N4gypY+0dNmbmNlx+skGRwxncjiHLV
          tWrfdl/7b0gg74vY2Zcq6t4=
    on_success: change
    on_failure: always
    on_start:   never
    on_cancel:  never
    on_error:   always

git:
  submodules: true

cache:
  apt: true
  ccache: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/ppa'
    packages:
      - g++-7
      - g++-8
      - g++-9
      - g++-10
      - lcov
      - cmake

arch:
  - arm64
  - s390x
  - ppc64le

env:
  - BUILD=coverage    CXX=g++-7  CC=gcc-7  BUILD_TYPE=Debug
  - BUILD=unit        CXX=g++-9  CC=gcc-9  BUILD_TYPE=Release CXXFLAGS="-std=c++2a"
  - BUILD=unit        CXX=g++-10 CC=gcc-10 BUILD_TYPE=Release CXXFLAGS="-std=c++17 -fconcepts"
  - BUILD=unit        CXX=g++-10 CC=gcc-10 BUILD_TYPE=Release
  - BUILD=unit        CXX=g++-8  CC=gcc-8  BUILD_TYPE=Release
  - BUILD=unit        CXX=g++-7  CC=gcc-7  BUILD_TYPE=Release
  - BUILD=performance CXX=g++-7  CC=gcc-7  BUILD_TYPE=Release
  - BUILD=header      CXX=g++-7  CC=gcc-7  BUILD_TYPE=Release
  - BUILD=snippet     CXX=g++-7  CC=gcc-7  BUILD_TYPE=Release

jobs:
  allow_failures:
    - os: linux
  fast_finish: true

install:
  - ccache --version
  - $CXX -v
  - cmake --version
  - |
    # use gcov7 matching the g++7 compiler
    if [[ "${BUILD}" =~ ^(coverage)$ ]]; then
      sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 100
    fi

before_script:
  - mkdir ../seqan3-build
  - cd ../seqan3-build
  - cmake ../seqan3/test/${BUILD} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - |
    if [[ "${BUILD}" =~ ^(unit|header|snippet|coverage)$ ]]; then
      make gtest_project
    fi
  - |
    if [[ "${BUILD}" =~ ^(performance)$ ]]; then
      make gbenchmark_project
    fi

script:
  - export SEQAN3_NO_VERSION_CHECK=1
  - export CCACHE_COMPRESS=true
  - export CCACHE_COMPRESSLEVEL=6
  - export CCACHE_MAXSIZE=5G
  - make -k -j2
  - |
    if [[ "${BUILD}" =~ ^(coverage)$ ]]; then
      : ; else
      if [[ "${BUILD}" =~ ^(snippet)$ ]]; then
        ctest . --output-on-failure]; else
        ctest . -j2 --output-on-failure
      fi
    fi

after_success:
  - |
    if test coverage = "${BUILD}"; then
      bash <(curl -s https://codecov.io/bash) -f ./seqan3_coverage -R "${TRAVIS_BUILD_DIR}" || echo 'Codecov failed to upload'
    fi

after_script:
  - ccache -s
